<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MsPelangganSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        DB::table('ms_pelanggan')->insert([
            // Data Pelanggan yang sudah ada
            [
                'id' => Str::uuid(),
                'nama' => 'Ahmad Fauzi',
                'no_telp' => '081234567890',
                'alamat' => 'Jl. Merdeka No. 1, Jakarta',
                'email' => 'ahmadfauzi@gmail.com',
                'nomor' => 1,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            // ... Data pelanggan sebelumnya (termasuk 20 pelanggan pertama)

            // 20 Pelanggan Baru
            [
                'id' => Str::uuid(),
                'nama' => 'Wawan Prasetyo',
                'no_telp' => '081234567123',
                'alamat' => 'Jl. Kenangan No. 21, Surabaya',
                'email' => 'wawanprasetyofirst@gmail.com',
                'nomor' => 21,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Zainab Ibrahim',
                'no_telp' => '082345671234',
                'alamat' => 'Jl. Suka Cita No. 22, Malang',
                'email' => 'zainabibrahim@gmail.com',
                'nomor' => 22,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Yosef Ramadhan',
                'no_telp' => '083456789987',
                'alamat' => 'Jl. Raya Timur No. 23, Jakarta',
                'email' => 'yoseframadhan@gmail.com',
                'nomor' => 23,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Aulia Safira',
                'no_telp' => '084567890876',
                'alamat' => 'Jl. Merpati No. 24, Bandung',
                'email' => 'aulia.safira@gmail.com',
                'nomor' => 24,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Benedictus Lionel',
                'no_telp' => '085678901234',
                'alamat' => 'Jl. Sukabumi No. 25, Surabaya',
                'email' => 'benedictusl@gmail.com',
                'nomor' => 25,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Carla Wijaya',
                'no_telp' => '086789012345',
                'alamat' => 'Jl. Raya Selatan No. 26, Medan',
                'email' => 'carlawijaya@gmail.com',
                'nomor' => 26,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Diana Kirana',
                'no_telp' => '087890123456',
                'alamat' => 'Jl. Merdeka No. 27, Surabaya',
                'email' => 'dianakirana@gmail.com',
                'nomor' => 27,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Eko Prasetyo',
                'no_telp' => '088901234567',
                'alamat' => 'Jl. Jendral Sudirman No. 28, Yogyakarta',
                'email' => 'ekoprasetyo@gmail.com',
                'nomor' => 28,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Farah Najwa',
                'no_telp' => '089012345678',
                'alamat' => 'Jl. Bali No. 29, Bali',
                'email' => 'farahnajwa@gmail.com',
                'nomor' => 29,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Gilang Hermawan',
                'no_telp' => '090123456789',
                'alamat' => 'Jl. Maju Jaya No. 30, Palembang',
                'email' => 'gilanghermawan@gmail.com',
                'nomor' => 30,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Hilda Sembiring',
                'no_telp' => '091234567890',
                'alamat' => 'Jl. Anggrek No. 31, Malang',
                'email' => 'hildasem@gmail.com',
                'nomor' => 31,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Ilham Putra',
                'no_telp' => '092345678901',
                'alamat' => 'Jl. Merpati No. 32, Surakarta',
                'email' => 'ilhamputra@gmail.com',
                'nomor' => 32,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Jasmine Putri',
                'no_telp' => '093456789012',
                'alamat' => 'Jl. Kemuning No. 33, Surabaya',
                'email' => 'jasmineputri@gmail.com',
                'nomor' => 33,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Kevin Fakhri',
                'no_telp' => '094567890123',
                'alamat' => 'Jl. Seroja No. 34, Jakarta',
                'email' => 'kevinfakhri@gmail.com',
                'nomor' => 34,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Lina Binti Nisa',
                'no_telp' => '095678901234',
                'alamat' => 'Jl. Taman No. 35, Semarang',
                'email' => 'linabnisa@gmail.com',
                'nomor' => 35,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Meli Anggraini',
                'no_telp' => '096789012345',
                'alamat' => 'Jl. Jendral Sudirman No. 36, Bandung',
                'email' => 'melianggraini@gmail.com',
                'nomor' => 36,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Nia Yuliana',
                'no_telp' => '097890123456',
                'alamat' => 'Jl. Anggrek No. 37, Surabaya',
                'email' => 'niayuliana@gmail.com',
                'nomor' => 37,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Oktavianus Arief',
                'no_telp' => '098901234567',
                'alamat' => 'Jl. Pahlawan No. 38, Palembang',
                'email' => 'oktavianusarief@gmail.com',
                'nomor' => 38,
                'dibuat_oleh' => 'admin',
                'diupdate_oleh' => 'admin',
                'tgl_dibuat' => $now,
                'tgl_diupdate' => $now,
                'status' => 'aktif',
            ],
        ]);
    }
}
